name: 'Deploy Delegates'
description: 'Parse and upload delegates information to a decentralized storage'
branding:
  icon: 'award'
  color: 'green'
inputs:
  delegates-folder:  # path to the delegates folder
    description: 'Path to the delegates folder'
    required: true
    default: 'governance/delegates'
  voting-committees-folder:  # path to the dvcs folder
    description: 'Path to the delegate voting committees folder'
    required: true
    default: 'governance/voting-committees'
  tags-file:  # path to the tags mapping file
    description: 'Path to the tags mapping file'
    required: true
    default: 'governance/delegates/meta/tags.json'
  web3-storage-token:
    description: 'web3.storage token'
    required: false
  nft-storage-token:
    description: 'nft.storage token'
    required: false
  output-file:
    description: 'The file that will be added to disk (leave empty for no output file)'
outputs:
  hash: # id of output
    description: 'Hash of the uploaded file'
runs:
  using: 'node16'
  main: 'lib/index.js'
