name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - add-back-node-modules
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run build

  test-unit: # run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run test
  test: # run the action, with data from __tests__ folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          delegates-folder: '__tests__/delegates'
          voting-committees-folder: '__tests__/voting-committees'
          tags-file: '__tests__/delegates/tags.json'
          output-file: '__tests__/meta/delegates.json'
          web3-storage-token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          nft-storage-token: ${{ secrets.NFT_STORAGE_TOKEN }}
